// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy0LtqO3yVRCnAlnS5otjqfz_lbfBesgU',
    appId: '1:1064308986376:web:8d120efe25eaeec50537bd',
    messagingSenderId: '1064308986376',
    projectId: 'vission-health-39cb2',
    authDomain: 'vission-health-39cb2.firebaseapp.com',
    storageBucket: 'vission-health-39cb2.firebasestorage.app',
    measurementId: 'G-60HFJPY9SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7wIQ6sJvsxIE7_Wcbgl2ElnrXHAbxVjY',
    appId: '1:1064308986376:android:105d5ed41413708e0537bd',
    messagingSenderId: '1064308986376',
    projectId: 'vission-health-39cb2',
    storageBucket: 'vission-health-39cb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_ca0EJ3TlgdOLjd6Pgd21zPi4Mjotz_0',
    appId: '1:1064308986376:ios:cb6412aa44942cd70537bd',
    messagingSenderId: '1064308986376',
    projectId: 'vission-health-39cb2',
    storageBucket: 'vission-health-39cb2.firebasestorage.app',
    iosBundleId: 'com.example.vissionHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_ca0EJ3TlgdOLjd6Pgd21zPi4Mjotz_0',
    appId: '1:1064308986376:ios:cb6412aa44942cd70537bd',
    messagingSenderId: '1064308986376',
    projectId: 'vission-health-39cb2',
    storageBucket: 'vission-health-39cb2.firebasestorage.app',
    iosBundleId: 'com.example.vissionHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy0LtqO3yVRCnAlnS5otjqfz_lbfBesgU',
    appId: '1:1064308986376:web:2c15d43da4446ca40537bd',
    messagingSenderId: '1064308986376',
    projectId: 'vission-health-39cb2',
    authDomain: 'vission-health-39cb2.firebaseapp.com',
    storageBucket: 'vission-health-39cb2.firebasestorage.app',
    measurementId: 'G-L3EWZY7573',
  );
}
